name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 6.0.1
          run_install: true
      - run: pnpm test
